function SpawnRegions()
	return {
		{ name = "Muldraugh, KY", file = "media/maps/Muldraugh, KY/spawnpoints.lua" },
		{ name = "Rosewood, KY", file = "media/maps/Rosewood, KY/spawnpoints.lua" },
		{ name = "West Point, KY", file = "media/maps/West Point, KY/spawnpoints.lua" },
		{ name = "Riverside, KY", file = "media/maps/Riverside, KY/spawnpoints.lua" },
		{ name = "InGameMaps_Main", file = "media/maps/InGameMaps_Main/spawnpoints.lua" },
		{ name = "BedfordFalls", file = "media/maps/BedfordFalls/spawnpoints.lua" },
		{ name = "North", file = "media/maps/North/spawnpoints.lua" },
		{ name = "South", file = "media/maps/South/spawnpoints.lua" },
		{ name = "West", file = "media/maps/West/spawnpoints.lua" },
		{ name = "BillionaireSafehouse", file = "media/maps/BillionaireSafehouse/spawnpoints.lua" },
		{ name = "CONRTF", file = "media/maps/CONRTF/spawnpoints.lua" },
		{ name = "CorOTRroad", file = "media/maps/CorOTRroad/spawnpoints.lua" },
		{ name = "EVAC_Muldraugh", file = "media/maps/EVAC_Muldraugh/spawnpoints.lua" },
		{ name = "FortRedstone", file = "media/maps/FortRedstone/spawnpoints.lua" },
		{ name = "Fort Rock Ridge", file = "media/maps/Fort Rock Ridge/spawnpoints.lua" },
		{ name = "MREX", file = "media/maps/MREX/spawnpoints.lua" },
		{ name = "MuldraughCheckpoint", file = "media/maps/MuldraughCheckpoint/spawnpoints.lua" },
		{ name = "Muldraugh Military Base", file = "media/maps/Muldraugh Military Base/spawnpoints.lua" },
		{ name = "li_township", file = "media/maps/li_township/spawnpoints.lua" },
		{ name = "orchidwood", file = "media/maps/orchidwood/spawnpoints.lua" },
		{ name = "Otr", file = "media/maps/Otr/spawnpoints.lua" },
		{ name = "Over the River - Secondary Route", file = "media/maps/Over the River - Secondary Route/spawnpoints.lua" },
		{ name = "RavenCreek", file = "media/maps/RavenCreek/spawnpoints.lua" },
		{ name = "Riverside Fire Department", file = "media/maps/Riverside Fire Department/spawnpoints.lua" },
		{ name = "Road from Monmouth County to Bedford Falls", file = "media/maps/Road from Monmouth County to Bedford Falls/spawnpoints.lua" },
		{ name = "Rosewood VHS Store", file = "media/maps/Rosewood VHS Store/spawnpoints.lua" },
		{ name = "Southwood2.0", file = "media/maps/Southwood2.0/spawnpoints.lua" },
		{ name = "The Compound", file = "media/maps/The Compound/spawnpoints.lua" },
		{ name = "Tugaland", file = "media/maps/Tugaland/spawnpoints.lua" },
		{ name = "west_point_expansion", file = "media/maps/west_point_expansion/spawnpoints.lua" },
		{ name = "WestPointExpansionFix", file = "media/maps/WestPointExpansionFix/spawnpoints.lua" },
		{ name = "Westwood", file = "media/maps/Westwood/spawnpoints.lua" },
		{ name = "AZSpawn", file = "media/maps/AZSpawn/spawnpoints.lua" },
		{ name = "Ashenwood", file = "media/maps/Ashenwood/spawnpoints.lua" },
		{ name = "Blackwood", file = "media/maps/Blackwood/spawnpoints.lua" },
		{ name = "FinneganAsylum", file = "media/maps/FinneganAsylum/spawnpoints.lua" },
		{ name = "Grapeseed", file = "media/maps/Grapeseed/spawnpoints.lua" },
		{ name = "NewEkron", file = "media/maps/NewEkron/spawnpoints.lua" },
		{ name = "Petroville", file = "media/maps/Petroville/spawnpoints.lua" },
		{ name = "Pitstop", file = "media/maps/Pitstop/spawnpoints.lua" },
		{ name = "pz_rosewoodexp_map", file = "media/maps/pz_rosewoodexp_map/spawnpoints.lua" },
		{ name = "The Museum", file = "media/maps/The Museum/spawnpoints.lua" },
		{ name = "Utopia", file = "media/maps/Utopia/spawnpoints.lua" },
		{ name = "WestPointTrailerParkAndVhsStore", file = "media/maps/WestPointTrailerParkAndVhsStore/spawnpoints.lua" },
		{ name = "Trelai_4x4", file = "media/maps/Trelai_4x4/spawnpoints.lua" },
		{ name = "Trelai_spawns", file = "media/maps/Trelai_spawns/spawnpoints.lua" },
		{ name = "Trelai_storyspawn", file = "media/maps/Trelai_storyspawn/spawnpoints.lua" },
		{ name = "Riverdeltabase", file = "media/maps/Riverdeltabase/spawnpoints.lua" },
		{ name = "Pertville", file = "media/maps/Pertville/spawnpoints.lua" },
		{ name = "Dirkerdam west", file = "media/maps/Dirkerdam west/spawnpoints.lua" },
		{ name = "Dirkerdam", file = "media/maps/Dirkerdam/spawnpoints.lua" },
		{ name = "Florius", file = "media/maps/Florius/spawnpoints.lua" },
		{ name = "Tashtego", file = "media/maps/Tashtego/spawnpoints.lua" },
		{ name = "Dirkerdam_Spawns", file = "media/maps/Dirkerdam_Spawns/spawnpoints.lua" },
		{ name = "Tandil", file = "media/maps/Tandil/spawnpoints.lua" },
		{ name = "Old Pine Village", file = "media/maps/Old Pine Village/spawnpoints.lua" },
		{ name = "Blueberry", file = "media/maps/Blueberry/spawnpoints.lua" },
		{ name = "Wilbore", file = "media/maps/Wilbore/spawnpoints.lua" },
		{ name = "Chinatown", file = "media/maps/Chinatown/spawnpoints.lua" },
		{ name = "Chinatown_EX", file = "media/maps/Chinatown_EX/spawnpoints.lua" },
		{ name = "MonmouthCounty", file = "media/maps/MonmouthCounty/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Interior", file = "media/maps/Xonics Mega Mall Interior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Exterior", file = "media/maps/Xonics Mega Mall Exterior/spawnpoints.lua" },
		{ name = "Xonics Mega Mall", file = "media/maps/Xonics Mega Mall/spawnpoints.lua" },
		{ name = "Xonics Mega Mall Roof", file = "media/maps/Xonics Mega Mall Roof/spawnpoints.lua" },
	}
end
